#Application Name
spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    #telling the server not to register himself in the service registry
    fetch-registry: false
    register-with-eureka: false
    
server:
  port: 8761